### ISSUE TITLE
Anything I can contribute?

### ISSUE THREAD

**Issue by kraj011** [Team6090/SwerveIO#6]
Hey! I've been checking out SwerveIO and it looks awesome! I love the way you're abstracting things to make a swerve implementation as easy as possible! Our team has not yet received our MK2 modules, but I was wondering if there was any sort of contributions you would be accepting that I can make without having the modules in hand! I would love to help out in any way I can!

**Comment by jordanbancino** [comment]
@kraj011 Welcome! Thank you so much! We'd love to have your contributions! If you're looking to use SwerveIO to drive your modules when you get them, we'll definitely want your feedback! We can work together to cover all the bases.

For now we're just waiting to test our code on our drive train, which will probably take a week or two, depending on when we meet next. So in the mean time just poke around in the code and familiarize yourself with it, and take a look at the issues page, we'll open issues for things we want done. And you're more than welcome to open your own issues and pull requests! If you have any questions, feel free to ask them here, and if you have any suggestions for us, we'd love to hear them! Thank you for your interest in our project!

**Comment by kraj011** [comment]
Absolutely! I look forward to hopefully contributing to this and helping make this the standard for all teams who use swerve!!

**Comment by jordanbancino** [comment]
@kraj011 I look forward to seeing what we can do!
